package org.goplanit.aurin.matsim.test;

import static org.junit.Assert.fail;

import java.io.File;
import java.net.URL;

import org.goplanit.aurin.matsim.PlanitAurinMatsimMain;
import org.junit.AfterClass;
import org.junit.Test;
import org.goplanit.utils.misc.FileUtils;
import org.goplanit.utils.misc.UrlUtils;
import org.goplanit.utils.resource.ResourceUtils;

/**
 * Test the PLANit MATSim simulation Wrapper for the AURIN platform for various car simulation and public transport as teleportation mode situations
 * 
 * @author markr
 *
 */
public class MatsimWrapperCarSimPtTeleportTest {
  
  //private static final URL NETWORK_URL = ResourceUtils.getResourceUrl("./Melbourne/car_pt_simple_melbourne_network.xml");
  private static final URL CLEANED_NETWORK_URL = ResourceUtils.getResourceUrl("./Melbourne/car_pt_simple_melbourne_network_cleaned.xml");
  private static final URL PLANS_URL = ResourceUtils.getResourceUrl("./Melbourne/plans_victoria_car_pt_tele.xml");
  private static final URL ACTIVITY_CONFIG_URL = ResourceUtils.getResourceUrl("./Melbourne/activity_config.xml");
  private static final URL PT_STOPS_CSV_URL = ResourceUtils.getResourceUrl("./Melbourne/melbourne_coarse_ptstops.csv");
  
  
  private static final File MATSIM_TMP_DIR = new File("./output/car_pt_tele_tmp");

  /**
   * Ensure that generated output files in tmp dir are cleaned up by deleting dirs and content because otherwise
   * we get errors dir could not be created for some reason
   */
  @AfterClass
  public static void afterClass(){
    FileUtils.deleteDirectory(MATSIM_TMP_DIR);
  }
  
  /**
   * Test with local inputs via command line call. We use public transport teleportation without considering stops here
   */
  @Test
  public void matsimSimulationWithPtWithoutStops() {
    try {
      
      int iterationsMax = 1;
      
      int linkStatsAverageInterval = 1;
      int linkStatsWriteInterval = 1;
        
      // java -jar PLANitAurinMatsim_version_.jar --type simulation --modes car_sim_pt_teleport --crs epsg:3112 
      //      --network "..\src\test\resources\Melbourne\car_pt_tele_simple_melbourne_network_cleaned.xml" --network_crs epsg:3112
      //      --plans "..\src\test\resources\Melbourne\plans_victoria_car_pt_tele.xml" --plans_crs epsg:3112 --activity_config
      //      "..\src\test\resources\Melbourne\activity_config.xml" --link_stats 1,1 --iterations_max 2
      PlanitAurinMatsimMain.main(
          new String[]{
              "--type",
              "simulation",
              "--modes",
              "car_sim_pt_teleport",
              "--crs",
              "epsg:3112",              
              "--network",
              UrlUtils.asLocalPath(CLEANED_NETWORK_URL).toString(),
              "--network_clean",
              "no",
              "--network_crs",
              "epsg:3112",
              "--plans",
              UrlUtils.asLocalPath(PLANS_URL).toString(),
              "--plans_crs",
              "epsg:3112",              
              "--activity_config",
              UrlUtils.asLocalPath(ACTIVITY_CONFIG_URL).toString(),
              "--link_stats",
              String.valueOf(linkStatsAverageInterval)+"," + String.valueOf(linkStatsWriteInterval),              
              "--iterations_max",
              String.valueOf(iterationsMax)});     
      
      
    } catch (Exception e) {
      e.printStackTrace();
      fail("Error when testing Aurin MATSim simulation Wrapper - MatsimWrapperCarSimPtTeleportTest");
    }
  }
  
  /**
   * Test with local inputs via command line call. Current plans file is already a sample, so no need to 
   * down sample scale at this point. We use public transport teleportation with considering stops activating the PtMatrixrouter of MATSim.
   * <p>
   * Since a stops file is created, the MATSimPTMatrixRouter is activated by default to base the pt travel times on a stop-to-stop travel time matrix
   * which is generated by MATSim (in absence of an explicitly provided one).
   * <p>
   * To make sure the simulation fits in the memory of a "normal" pc, we provided a stops file only containing bus and train stops leaving out tram stops, to minimise
   * the size of the stop-to-stop matrix. 
   */
  @Test
  public void matsimSimulationWithPtWithStops() {
    try {
      
      final int iterationsMax = 1;
      
      final int linkStatsAverageInterval = 1;
      final int linkStatsWriteInterval = 1;
        
      // java -jar PLANitAurinMatsim_version_.jar --type simulation --modes car_sim_pt_teleport --crs epsg:3112 
      //      --network "..\src\test\resources\Melbourne\car_pt_tele_simple_melbourne_network_cleaned.xml" --network_crs epsg:3112
      //      --plans "..\src\test\resources\Melbourne\plans_victoria_car_pt_tele.xml" --plans_crs epsg:3112 --activity_config
      //      "..\src\test\resources\Melbourne\activity_config.xml" --link_stats 1,1 --pt-stops-csv "./Melbourne/melbourne_coarse_ptstops.csv" --iterations_max 2
      PlanitAurinMatsimMain.main(
          new String[]{
              "--type",
              "simulation",
              "--modes",
              "car_sim_pt_teleport",
              "--crs",
              "epsg:3112",              
              "--network",
              UrlUtils.asLocalPath(CLEANED_NETWORK_URL).toString(),
              "--network_clean",
              "no",
              "--network_crs",
              "epsg:3112",
              "--plans",
              UrlUtils.asLocalPath(PLANS_URL).toString(),
              "--plans_crs",
              "epsg:3112",              
              "--activity_config",
              UrlUtils.asLocalPath(ACTIVITY_CONFIG_URL).toString(),
              "--link_stats",
              String.valueOf(linkStatsAverageInterval)+"," + String.valueOf(linkStatsWriteInterval),
              "--pt-stops-csv",
              UrlUtils.asLocalPath(PT_STOPS_CSV_URL).toString(),
              "--iterations_max",
              String.valueOf(iterationsMax)});     
            
    } catch (Exception e) {
      e.printStackTrace();
      fail("Error when testing Aurin MATSim simulation Wrapper - MatsimWrapperCarSimPtTeleportTest");
    }
  }  
  
  /**
   * Test to generate a configuration file based on the wrapper's tailored config file and the additional command line
   * options provided by the user (if any). The user can then make custom changes and use the config file to run a simulation
   * via this wrapper at a later stage
   * 
   */
  @Test
  public void matsimTemplateConfigGenerator() {
    try {  
        
      int iterationsMax = 250;
      
      PlanitAurinMatsimMain.main(
          new String[]{
              "--type",
              "config",
              "--modes",
              "car_sim_pt_teleport",
              "--iterations_max",
              String.valueOf(iterationsMax)});      
      
    } catch (Exception e) {
      e.printStackTrace();
      fail("Error when testing Aurin MATSim simulation Wrapper - MatsimWrapperCarSimPtTeleportTest");
    }
  }

}

